compute:
  name: llm-inspect-cluster
environment:
  name: llm-eval-cpu-ubuntu-base-plus-conda-py310
  description: "Environment created from AML CPU Ubuntu base Docker image plus Conda environment."
  base_image_name: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  conda_file_path: ./environments/conda.yml
datastore:
  gold_zone: azureml://datastores/goldzone/paths/
  evaluation: azureml://datastores/evaluation/paths/
  human_eval:
    batch_status_table: human_eval_batch_status
    tasks_tracker: azureml://datastores/humanevaluation/paths/