name: llm-evaluation-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
    - azure-ai-ml==1.12.1
    - azure-identity==1.15.0
    - azure-keyvault-secrets==4.7.0
    - azureml-dataprep[pandas]
    - mltable
    - numpy==1.26.2
    - pandas
    - pyodbc==5.0.1
    - azureml-mlflow==1.54.0
    - tenacity==8.2.3
    - taskmonk-sdk==0.29